SELECT O.ANIMAL_ID, O.NAME FROM ANIMAL_OUTS AS O
    INNER JOIN ANIMAL_INS AS I
    ON I.ANIMAL_ID=O.ANIMAL_ID AND O.DATETIME<I.DATETIME ORDER BY I.DATETIME;


# ANIMAL_OUTS(입양테이블)에서 ANIMAL_INS(보호소 테이블)의 ANIMAL_ID를 FK로 가져온다고 하니, INNER JOIN(교집합)을 통해 PK=FK를 해주고, 조건(입양시기<보호시기)에 해당하는 데이터를 가져옴. (가져오는 데이터의 칼럼은 ANIMAL_ID와 NAME)