SELECT E.DEPT_ID, D.DEPT_NAME_EN, ROUND(AVG(SAL), 0) AS AVG_SAL 
    FROM HR_EMPLOYEES AS E JOIN HR_DEPARTMENT AS D ON E.DEPT_ID=D.DEPT_ID
    GROUP BY DEPT_ID
    ORDER BY AVG_SAL DESC;
    
# HR_EMPOLYEES 테이블과 HR_DEPARTMENT 테이블 JOIN한 이유 : DEPT_NAME_EN 가져오기 위함.
# GROUP BY절을 통해 부서별로 그룹화
# 숫자함수 ROUND를 이용하여 소숫점 첫째 자리 반올림
# ORDER BY절을 통해 평균연봉 내림차순(DESC) 정렬